name: Notify slack workflow

on:
  workflow_run:
    workflows:
      - Run tests workflow
      - Build release workflow
    types:
      - completed

jobs:
  notify_slack:
    runs-on: ubuntu-18.04
    name: Notify slack
    steps:
      - name: Notify slack
        uses: zebra-lucky/actions-js-slackJobsStatus@0.0.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          gh_ctx: ${{ toJson(github) }}
          token: ${{ secrets.GITHUB_TOKEN }}
